### ISSUE TITLE
renderSidebar causing InvalidArgumentException

### ISSUE THREAD

**Issue by ghost** [Hutchy68/pivot#105]
### Setup

- Browsers and versions: Chrome
- MediaWiki version: 1.35
- PHP version: 7.3
- Pivot version: 2.3.0

### Issue

When loading MediaWiki with Pivot, I'm getting the following error from Pivot.skin.php:

`Original exception: [X9wuahHz4QTVHaVJrsiPNwADBgc] /wiki/Main_Page InvalidArgumentException from line 263 of /home/botcadmin/public_html/wiki/includes/language/Message.php: $key must be a string or an array
Backtrace:
#0 /home/botcadmin/public_html/wiki/includes/GlobalFunctions.php(1221): Message->__construct(integer)
#1 /home/botcadmin/public_html/wiki/includes/context/RequestContext.php(447): wfMessage(integer)
#2 /home/botcadmin/public_html/wiki/includes/context/ContextSource.php(185): RequestContext->msg(integer)
#3 /home/botcadmin/public_html/wiki/includes/skins/Skin.php(2232): ContextSource->msg(integer)
#4 /home/botcadmin/public_html/wiki/includes/skins/Skin.php(2368): Skin->makeLink(integer, array, array)
#5 /home/botcadmin/public_html/wiki/includes/skins/BaseTemplate.php(262): Skin->makeListItem(integer, array, array)
#6 /home/botcadmin/public_html/wiki/skins/pivot/Pivot.skin.php(300): BaseTemplate->makeListItem(integer, array)
#7 /home/botcadmin/public_html/wiki/skins/pivot/Pivot.skin.php(126): pivotTemplate->renderSidebar()
#8 /home/botcadmin/public_html/wiki/includes/skins/SkinTemplate.php(129): pivotTemplate->execute()
#9 /home/botcadmin/public_html/wiki/includes/skins/SkinTemplate.php(144): SkinTemplate->generateHTML()
#10 /home/botcadmin/public_html/wiki/includes/OutputPage.php(2615): SkinTemplate->outputPage()
#11 /home/botcadmin/public_html/wiki/includes/MediaWiki.php(947): OutputPage->output(boolean)
#12 /home/botcadmin/public_html/wiki/includes/MediaWiki.php(960): MediaWiki->{closure}()
#13 /home/botcadmin/public_html/wiki/includes/MediaWiki.php(543): MediaWiki->main()
#14 /home/botcadmin/public_html/wiki/index.php(53): MediaWiki->run()
#15 /home/botcadmin/public_html/wiki/index.php(46): wfIndexMain()
#16 {main}
`

Removing renderSidebar() stops the error, but then obviously the sidebar doesn't render.

**Comment by ghost** [comment]
On further investigation, was an unrelated function in LocalSettings causing the trouble. Pls disregard!
