### ISSUE TITLE
undefined function wfSuppressWarnings

### ISSUE THREAD

**Issue by MarcHagen** [Hutchy68/pivot#92]
### Setup

- Browsers and versions: Chrome 
- MediaWiki version: 1.34
- Database version: MariaDB 10.4
- PHP version: PHP 7.3.15
- Pivot version: git:master
- Extension version (if connected to the issue): 

### Issue

Getting a 500 Internal error.
I belief #90 is the fix for this.

```
PHP Fatal error:  Uncaught Error: Call to undefined function wfSuppressWarnings() in /home/<snip>/public_html/skins/pivot/Pivot.skin.php:63, referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
Stack trace:, referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#0 /home/<snip>/public_html/includes/skins/SkinTemplate.php(217): pivotTemplate->execute(), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#1 /home/<snip>/public_html/includes/OutputPage.php(2574): SkinTemplate->outputPage(), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#2 /home/<snip>/public_html/includes/exception/MWExceptionRenderer.php(134): OutputPage->output(), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#3 /home/<snip>/public_html/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error)), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#4 /home/<snip>/public_html/includes/exception/MWExceptionHandler.php(121): MWExceptionRenderer::output(Object(Error), 2), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#5 /home/<snip>/public_html/includes/exception/MWExceptionHandler.php(195): MWExceptionHandler::report(Object(Error)), referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
#6 /home/<snip>/pub in /home/<snip>/public_html/skins/pivot/Pivot.skin.php on line 63, referer: https://wiki.<snip>.nl/index.php?title=Hoofdpagina
```

**Comment by Hutchy68** [comment]
Fixed in Release v2.2.0, or pull master or develop
